FROM python:3.10-slim

# System deps
RUN apt-get update && apt-get install -y \
    ffmpeg \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install CCExtractor (stable binary)
RUN wget https://github.com/CCExtractor/ccextractor/releases/latest/download/ccextractor-linux.zip \
    && unzip ccextractor-linux.zip \
    && mv ccextractor /usr/local/bin/ccextractor \
    && chmod +x /usr/local/bin/ccextractor \
    && rm -rf ccextractor-linux.zip

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 10000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]