FROM python:3.10-slim

# System deps
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install ccextractor properly
RUN git clone https://github.com/CCExtractor/ccextractor.git \
    && cd ccextractor/linux \
    && ./build

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]